//! Autogenerated weights for pallet_tokenomics
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI
//! DATE: 2025-01-01, STEPS: `50`, REPEAT: `20`

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_tokenomics.
pub trait WeightInfo {
    fn on_finalize() -> Weight;
    fn record_transaction() -> Weight;
    fn record_fee_burn() -> Weight;
    fn force_era_end() -> Weight;
}

/// Weights for pallet_tokenomics using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: Tokenomics EffectiveBlockHeight (r:1 w:1)
    /// Storage: Tokenomics NetworkActivity (r:1 w:0)
    /// Storage: Tokenomics TotalMinted (r:1 w:1)
    /// Storage: Tokenomics LastEraBlock (r:1 w:0)
    fn on_finalize() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `142`
        //  Estimated: `3607`
        // Minimum execution time: 25_000_000 picoseconds.
        Weight::from_parts(30_000_000, 3607)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Storage: Tokenomics EraTransactionVolume (r:1 w:1)
    /// Storage: Tokenomics EraActiveAccounts (r:1 w:1)
    fn record_transaction() -> Weight {
        Weight::from_parts(10_000_000, 1024)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Storage: Tokenomics EraFeesBurned (r:1 w:1)
    fn record_fee_burn() -> Weight {
        Weight::from_parts(8_000_000, 1024)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: Tokenomics (all era storages) (r:5 w:5)
    fn force_era_end() -> Weight {
        Weight::from_parts(40_000_000, 5120)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
    }
}

// For benchmarks
impl WeightInfo for () {
    fn on_finalize() -> Weight {
        Weight::from_parts(30_000_000, 3607)
    }

    fn record_transaction() -> Weight {
        Weight::from_parts(10_000_000, 1024)
    }

    fn record_fee_burn() -> Weight {
        Weight::from_parts(8_000_000, 1024)
    }

    fn force_era_end() -> Weight {
        Weight::from_parts(40_000_000, 5120)
    }
}
